name: Deploy Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, mazorya]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker
        run: |
          docker compose down
          docker compose up -d --build