name: Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, mazorya]

    steps:
      - name: Test Runner
        run: |
          echo "RUNNER IS WORKING"
          hostname
          whoami
          docker --version